import ROOT 

CENT_MINS = [0,     0,  1,  10, 30, 50, 70]
CENT_MAXS = [100,   1,  10, 30, 50, 70, 100]

if __name__=='__main__':

    ROOT.gStyle.SetOptLogy()

    infileMC = ROOT.TFile.Open("/home/fchinu/Run3/Ds_pp_13TeV/Datasets/Ds_pp_run3_ml/MC/Train252070/LHC24d3b_AnalysisResults.root")
    hMultMCAll = infileMC.Get("hf-task-ds/Data/hNPvContribAll")
    hMultMCAll.SetDirectory(0)
    hMultMCDsPromptCands = infileMC.Get("hf-task-ds/MC/Ds/Prompt/hNPvContribCands")
    hMultMCDsPromptCands.SetDirectory(0)
    hMultMCDsPromptCandsInSignalRegion = infileMC.Get("hf-task-ds/MC/Ds/Prompt/hNPvContribCandsInSignalRegionDs")
    hMultMCDsPromptCandsInSignalRegion.SetDirectory(0)
    hMultMCDsNonPromptCands = infileMC.Get("hf-task-ds/MC/Ds/NonPrompt/hNPvContribCands")
    hMultMCDsNonPromptCands.SetDirectory(0)
    hMultMCDsNonPromptCandsInSignalRegion = infileMC.Get("hf-task-ds/MC/Ds/NonPrompt/hNPvContribCandsInSignalRegionDs")
    hMultMCDsNonPromptCandsInSignalRegion.SetDirectory(0)
    hMultMCDplusPromptCands = infileMC.Get("hf-task-ds/MC/Dplus/Prompt/hNPvContribCands")
    hMultMCDplusPromptCands.SetDirectory(0)
    hMultMCDplusPromptCandsInSignalRegion = infileMC.Get("hf-task-ds/MC/Dplus/Prompt/hNPvContribCandsInSignalRegionDplus")
    hMultMCDplusPromptCandsInSignalRegion.SetDirectory(0)
    hMultMCDplusNonPromptCands = infileMC.Get("hf-task-ds/MC/Dplus/NonPrompt/hNPvContribCands")
    hMultMCDplusNonPromptCands.SetDirectory(0)
    hMultMCDplusNonPromptCandsInSignalRegion = infileMC.Get("hf-task-ds/MC/Dplus/NonPrompt/hNPvContribCandsInSignalRegionDplus")
    hMultMCDplusNonPromptCandsInSignalRegion.SetDirectory(0)
    infileMC.Close()

    infileData = ROOT.TFile.Open("/home/fchinu/Run3/Ds_pp_13TeV/Datasets/Ds_pp_run3_ml/Data/Train252059/LHC22o_AnalysisResults.root")
    hMultData = infileData.Get("hf-task-ds/Data/hNPvContribAll")
    hMultData.SetDirectory(0)
    hMultDataCands = infileData.Get("hf-task-ds/Data/hNPvContribCands")
    hMultDataCands.SetDirectory(0)
    hMultDataCandsInSignalRegionDs = infileData.Get("hf-task-ds/Data/hNPvContribCandsInSignalRegionDs")
    hMultDataCandsInSignalRegionDs.SetDirectory(0)
    hMultDataCandsInSignalRegionDplus = infileData.Get("hf-task-ds/Data/hNPvContribCandsInSignalRegionDplus")
    hMultDataCandsInSignalRegionDplus.SetDirectory(0)
    infileData.Close()

    hMultMCAllProjected = hMultMCAll.ProjectionX("hMultMCAllProjected", 0, -1, "e")
    hMultMCAllProjected.Scale(1./hMultMCAllProjected.Integral())
    hMultMCDsPromptCandsProjected = hMultMCDsPromptCands.ProjectionX("hMultMCDsPromptCandsProjected", 0, -1, "e")
    hMultMCDsPromptCandsProjected.Scale(1./hMultMCDsPromptCandsProjected.Integral())
    hMultMCDsPromptCandsInSignalRegionProjected = hMultMCDsPromptCandsInSignalRegion.ProjectionX("hMultMCDsPromptCandsInSignalRegionProjected", 0, -1, "e")
    hMultMCDsPromptCandsInSignalRegionProjected.Scale(1./hMultMCDsPromptCandsInSignalRegionProjected.Integral())
    hMultMCDsNonPromptCandsProjected = hMultMCDsNonPromptCands.ProjectionX("hMultMCDsNonPromptCandsProjected", 0, -1, "e")
    hMultMCDsNonPromptCandsProjected.Scale(1./hMultMCDsNonPromptCandsProjected.Integral())
    hMultMCDsNonPromptCandsInSignalRegionProjected = hMultMCDsNonPromptCandsInSignalRegion.ProjectionX("hMultMCDsNonPromptCandsInSignalRegionProjected", 0, -1, "e")
    hMultMCDsNonPromptCandsInSignalRegionProjected.Scale(1./hMultMCDsNonPromptCandsInSignalRegionProjected.Integral())
    hMultMCDplusPromptCandsProjected = hMultMCDplusPromptCands.ProjectionX("hMultMCDplusPromptCandsProjected", 0, -1, "e")
    hMultMCDplusPromptCandsProjected.Scale(1./hMultMCDplusPromptCandsProjected.Integral())
    hMultMCDplusPromptCandsInSignalRegionProjected = hMultMCDplusPromptCandsInSignalRegion.ProjectionX("hMultMCDplusPromptCandsInSignalRegionProjected", 0, -1, "e")
    hMultMCDplusPromptCandsInSignalRegionProjected.Scale(1./hMultMCDplusPromptCandsInSignalRegionProjected.Integral())
    hMultMCDplusNonPromptCandsProjected = hMultMCDplusNonPromptCands.ProjectionX("hMultMCDplusNonPromptCandsProjected", 0, -1, "e")
    hMultMCDplusNonPromptCandsProjected.Scale(1./hMultMCDplusNonPromptCandsProjected.Integral())
    hMultMCDplusNonPromptCandsInSignalRegionProjected = hMultMCDplusNonPromptCandsInSignalRegion.ProjectionX("hMultMCDplusNonPromptCandsInSignalRegionProjected", 0, -1, "e")
    hMultMCDplusNonPromptCandsInSignalRegionProjected.Scale(1./hMultMCDplusNonPromptCandsInSignalRegionProjected.Integral())

    hMultMCAllProjected.SetMarkerStyle(ROOT.kFullDiamond)
    hMultMCDsPromptCandsProjected.SetMarkerStyle(ROOT.kFullDiamond)
    hMultMCDsPromptCandsInSignalRegionProjected.SetMarkerStyle(ROOT.kFullDiamond)
    hMultMCDsNonPromptCandsProjected.SetMarkerStyle(ROOT.kFullDiamond)
    hMultMCDsNonPromptCandsInSignalRegionProjected.SetMarkerStyle(ROOT.kFullDiamond)
    hMultMCDplusPromptCandsProjected.SetMarkerStyle(ROOT.kFullDiamond)
    hMultMCDplusPromptCandsInSignalRegionProjected.SetMarkerStyle(ROOT.kFullDiamond)
    hMultMCDplusNonPromptCandsProjected.SetMarkerStyle(ROOT.kFullDiamond)
    hMultMCDplusNonPromptCandsInSignalRegionProjected.SetMarkerStyle(ROOT.kFullDiamond)
    hMultMCAllProjected.SetMarkerColor(ROOT.kAzure+3)
    hMultMCDsPromptCandsProjected.SetMarkerColor(ROOT.kAzure+3)
    hMultMCDsPromptCandsInSignalRegionProjected.SetMarkerColor(ROOT.kAzure+3)
    hMultMCDsNonPromptCandsProjected.SetMarkerColor(ROOT.kAzure+3)
    hMultMCDsNonPromptCandsInSignalRegionProjected.SetMarkerColor(ROOT.kAzure+3)
    hMultMCDplusPromptCandsProjected.SetMarkerColor(ROOT.kAzure+3)
    hMultMCDplusPromptCandsInSignalRegionProjected.SetMarkerColor(ROOT.kAzure+3)
    hMultMCDplusNonPromptCandsProjected.SetMarkerColor(ROOT.kAzure+3)
    hMultMCDplusNonPromptCandsInSignalRegionProjected.SetMarkerColor(ROOT.kAzure+3)
        

    outfile = ROOT.TFile.Open("/home/fchinu/Run3/Ds_pp_13TeV/Efficiency/VsMult/Mult_weights.root", "RECREATE")
    for cent_min, cent_max in zip(CENT_MINS,CENT_MAXS):
        hMultData.GetYaxis().SetRangeUser(cent_min, cent_max)
        hMultDataCands.GetYaxis().SetRangeUser(cent_min, cent_max)
        hMultDataCandsInSignalRegionDs.GetYaxis().SetRangeUser(cent_min, cent_max)
        hMultDataCandsInSignalRegionDplus.GetYaxis().SetRangeUser(cent_min, cent_max)

        hMultDataProjected = hMultData.ProjectionX(f"hMultDataProjected_{cent_min}_{cent_max}", 0, -1, "e")
        hMultDataProjected.Scale(1./hMultDataProjected.Integral())
        hMultDataCandsProjected = hMultDataCands.ProjectionX(f"hMultDataCandsProjected_{cent_min}_{cent_max}", 0, -1, "e")
        hMultDataCandsProjected.Scale(1./hMultDataCandsProjected.Integral())
        hMultDataCandsInSignalRegionDsProjected = hMultDataCandsInSignalRegionDs.ProjectionX(f"hMultDataCandsInSignalRegionDsProjected_{cent_min}_{cent_max}", 0, -1, "e")
        hMultDataCandsInSignalRegionDsProjected.Scale(1./hMultDataCandsInSignalRegionDsProjected.Integral())
        hMultDataCandsInSignalRegionDplusProjected = hMultDataCandsInSignalRegionDplus.ProjectionX(f"hMultDataCandsInSignalRegionDplusProjected_{cent_min}_{cent_max}", 0, -1, "e")
        hMultDataCandsInSignalRegionDplusProjected.Scale(1./hMultDataCandsInSignalRegionDplusProjected.Integral())

        hMultDataProjected.SetMarkerStyle(ROOT.kFullCircle)
        hMultDataCandsProjected.SetMarkerStyle(ROOT.kFullCircle)
        hMultDataCandsInSignalRegionDsProjected.SetMarkerStyle(ROOT.kFullCircle)
        hMultDataCandsInSignalRegionDplusProjected.SetMarkerStyle(ROOT.kFullCircle)
        hMultDataProjected.SetMarkerColor(ROOT.kRed)
        hMultDataCandsProjected.SetMarkerColor(ROOT.kRed)
        hMultDataCandsInSignalRegionDsProjected.SetMarkerColor(ROOT.kRed)
        hMultDataCandsInSignalRegionDplusProjected.SetMarkerColor(ROOT.kRed)
        hMultDataProjected.SetLineColor(ROOT.kRed)
        hMultDataCandsProjected.SetLineColor(ROOT.kRed)
        hMultDataCandsInSignalRegionDsProjected.SetLineColor(ROOT.kRed)
        hMultDataCandsInSignalRegionDplusProjected.SetLineColor(ROOT.kRed)

        hMultDataProjected.Write()
        hMultDataCandsProjected.Write()
        hMultDataCandsInSignalRegionDsProjected.Write()
        hMultDataCandsInSignalRegionDplusProjected.Write()

        hWeightAll = hMultDataProjected.Clone(f"hWeightAll_{cent_min}_{cent_max}")
        hWeightAll.SetTitle("Weights;N_{PV};Weight")
        hWeightAll.Divide(hMultMCAllProjected)
        hWeightDsPromptCands = hMultDataCandsProjected.Clone(f"hWeightDsPromptCands_{cent_min}_{cent_max}")
        hWeightDsPromptCands.SetTitle("Weights;N_{PV};Weight")
        hWeightDsPromptCands.Divide(hMultMCDsPromptCandsProjected)
        hWeightDsPromptCandsInSignalRegion = hMultDataCandsInSignalRegionDsProjected.Clone(f"hWeightDsPromptCandsInSignalRegion_{cent_min}_{cent_max}")
        hWeightDsPromptCandsInSignalRegion.SetTitle("Weights;N_{PV};Weight")
        hWeightDsPromptCandsInSignalRegion.Divide(hMultMCDsPromptCandsInSignalRegionProjected)
        hWeightDsNonPromptCands = hMultDataCandsProjected.Clone(f"hWeightDsNonPromptCands_{cent_min}_{cent_max}")
        hWeightDsNonPromptCands.Divide(hMultMCDsNonPromptCandsProjected)
        hWeightDsNonPromptCandsInSignalRegion = hMultDataCandsInSignalRegionDsProjected.Clone(f"hWeightDsNonPromptCandsInSignalRegion_{cent_min}_{cent_max}")
        hWeightDsNonPromptCandsInSignalRegion.SetTitle("Weights;N_{PV};Weight")
        hWeightDsNonPromptCandsInSignalRegion.Divide(hMultMCDsNonPromptCandsInSignalRegionProjected)
        hWeightDplusPromptCands = hMultDataCandsProjected.Clone(f"hWeightDplusPromptCands_{cent_min}_{cent_max}")
        hWeightDplusPromptCands.Divide(hMultMCDplusPromptCandsProjected)
        hWeightDplusPromptCandsInSignalRegion = hMultDataCandsInSignalRegionDplusProjected.Clone(f"hWeightDplusPromptCandsInSignalRegion_{cent_min}_{cent_max}")
        hWeightDplusPromptCandsInSignalRegion.SetTitle("Weights;N_{PV};Weight")
        hWeightDplusPromptCandsInSignalRegion.Divide(hMultMCDplusPromptCandsInSignalRegionProjected)
        hWeightDplusNonPromptCands = hMultDataCandsProjected.Clone(f"hWeightDplusNonPromptCands_{cent_min}_{cent_max}")
        hWeightDplusNonPromptCands.SetTitle("Weights;N_{PV};Weight")
        hWeightDplusNonPromptCands.Divide(hMultMCDplusNonPromptCandsProjected)
        hWeightDplusNonPromptCandsInSignalRegion = hMultDataCandsInSignalRegionDplusProjected.Clone(f"hWeightDplusNonPromptCandsInSignalRegion_{cent_min}_{cent_max}")
        hWeightDplusNonPromptCandsInSignalRegion.SetTitle("Weights;N_{PV};Weight")
        hWeightDplusNonPromptCandsInSignalRegion.Divide(hMultMCDplusNonPromptCandsInSignalRegionProjected)

        canvasDsPrompt = ROOT.TCanvas(f"canvasDsPrompt_{cent_min}_{cent_max}", f"canvasDsPrompt_{cent_min}_{cent_max}", 800, 600)
        canvasDsPrompt.Divide(3,2)
        canvasDsPrompt.cd(1)
        minRangeY = min(hMultDataProjected.GetMinimum(), hMultMCAllProjected.GetMinimum())
        maxRangeY = max(hMultDataProjected.GetMaximum(), hMultMCAllProjected.GetMaximum())
        minRangeX = hMultDataProjected.GetXaxis().GetBinLowEdge(1)
        maxRangeX = hMultDataProjected.GetXaxis().GetBinLowEdge(hMultDataProjected.GetNbinsX()+1)
        ROOT.gPad.DrawFrame(minRangeX, minRangeY*0.9, maxRangeX, maxRangeY*1.1, "All events;N_{PV};Counts")
        hMultDataProjected.Draw("same")
        hMultMCAllProjected.Draw("same")
        canvasDsPrompt.cd(2)
        minRangeY = min(hMultDataCandsProjected.GetMinimum(), hMultMCDsPromptCandsProjected.GetMinimum())
        maxRangeY = max(hMultDataCandsProjected.GetMaximum(), hMultMCDsPromptCandsProjected.GetMaximum())
        minRangeX = hMultDataCandsProjected.GetXaxis().GetBinLowEdge(1)
        maxRangeX = hMultDataCandsProjected.GetXaxis().GetBinLowEdge(hMultDataCandsProjected.GetNbinsX()+1)
        ROOT.gPad.DrawFrame(minRangeX, minRangeY*0.9, maxRangeX, maxRangeY*1.1, "Events with Ds cand;N_{PV};Counts")
        hMultDataCandsProjected.Draw("same")
        hMultMCDsPromptCandsProjected.Draw("same")
        canvasDsPrompt.cd(3)
        minRangeY = min(hMultDataCandsInSignalRegionDsProjected.GetMinimum(), hMultMCDsPromptCandsInSignalRegionProjected.GetMinimum())
        maxRangeY = max(hMultDataCandsInSignalRegionDsProjected.GetMaximum(), hMultMCDsPromptCandsInSignalRegionProjected.GetMaximum())
        minRangeX = hMultDataCandsInSignalRegionDsProjected.GetXaxis().GetBinLowEdge(1)
        maxRangeX = hMultDataCandsInSignalRegionDsProjected.GetXaxis().GetBinLowEdge(hMultDataCandsInSignalRegionDsProjected.GetNbinsX()+1)
        ROOT.gPad.DrawFrame(minRangeX, minRangeY*0.9, maxRangeX, maxRangeY*1.1, "Events with Ds cand in mass region;N_{PV};Counts")
        hMultDataCandsInSignalRegionDsProjected.Draw("same")
        hMultMCDsPromptCandsInSignalRegionProjected.Draw("same")
        canvasDsPrompt.cd(4)
        hWeightAll.Draw()
        canvasDsPrompt.cd(5)
        hWeightDsPromptCands.Draw()
        canvasDsPrompt.cd(6)
        hWeightDsPromptCandsInSignalRegion.Draw()
        canvasDsPrompt.Write()

        canvasDsNonPrompt = ROOT.TCanvas(f"canvasDsNonPrompt_{cent_min}_{cent_max}", f"canvasDsNonPrompt_{cent_min}_{cent_max}", 800, 600)
        canvasDsNonPrompt.Divide(3,2)
        canvasDsNonPrompt.cd(1)
        minRangeY = min(hMultDataProjected.GetMinimum(), hMultMCAllProjected.GetMinimum())
        maxRangeY = max(hMultDataProjected.GetMaximum(), hMultMCAllProjected.GetMaximum())
        minRangeX = hMultDataProjected.GetXaxis().GetBinLowEdge(1)
        maxRangeX = hMultDataProjected.GetXaxis().GetBinLowEdge(hMultDataProjected.GetNbinsX()+1)
        ROOT.gPad.DrawFrame(minRangeX, minRangeY*0.9, maxRangeX, maxRangeY*1.1, "All events;N_{PV};Counts")
        hMultDataProjected.Draw("same")
        hMultMCAllProjected.Draw("same")
        canvasDsNonPrompt.cd(2)
        minRangeY = min(hMultDataCandsProjected.GetMinimum(), hMultMCDsNonPromptCandsProjected.GetMinimum())
        maxRangeY = max(hMultDataCandsProjected.GetMaximum(), hMultMCDsNonPromptCandsProjected.GetMaximum())
        minRangeX = hMultDataCandsProjected.GetXaxis().GetBinLowEdge(1)
        maxRangeX = hMultDataCandsProjected.GetXaxis().GetBinLowEdge(hMultDataCandsProjected.GetNbinsX()+1)
        ROOT.gPad.DrawFrame(minRangeX, minRangeY*0.9, maxRangeX, maxRangeY*1.1, "Events with Ds cand;N_{PV};Counts")
        hMultDataCandsProjected.Draw("same")
        hMultMCDsNonPromptCandsProjected.Draw("same")
        canvasDsNonPrompt.cd(3)
        minRangeY = min(hMultDataCandsInSignalRegionDsProjected.GetMinimum(), hMultMCDsNonPromptCandsInSignalRegionProjected.GetMinimum())
        maxRangeY = max(hMultDataCandsInSignalRegionDsProjected.GetMaximum(), hMultMCDsNonPromptCandsInSignalRegionProjected.GetMaximum())
        minRangeX = hMultDataCandsInSignalRegionDsProjected.GetXaxis().GetBinLowEdge(1)
        maxRangeX = hMultDataCandsInSignalRegionDsProjected.GetXaxis().GetBinLowEdge(hMultDataCandsInSignalRegionDsProjected.GetNbinsX()+1)
        ROOT.gPad.DrawFrame(minRangeX, minRangeY*0.9, maxRangeX, maxRangeY*1.1, "Events with Ds cand in mass region;N_{PV};Counts")
        hMultDataCandsInSignalRegionDsProjected.Draw("same")
        hMultMCDsNonPromptCandsInSignalRegionProjected.Draw("same")
        canvasDsNonPrompt.cd(4)
        hWeightAll.Draw()
        canvasDsNonPrompt.cd(5)
        hWeightDsNonPromptCands.Draw()
        canvasDsNonPrompt.cd(6)
        hWeightDsNonPromptCandsInSignalRegion.Draw()
        canvasDsNonPrompt.Write()

        canvasDplusPrompt = ROOT.TCanvas(f"canvasDplusPrompt_{cent_min}_{cent_max}", f"canvasDplusPrompt_{cent_min}_{cent_max}", 800, 600)
        canvasDplusPrompt.Divide(3,2)
        canvasDplusPrompt.cd(1)
        minRangeY = min(hMultDataProjected.GetMinimum(), hMultMCAllProjected.GetMinimum())
        maxRangeY = max(hMultDataProjected.GetMaximum(), hMultMCAllProjected.GetMaximum())
        minRangeX = hMultDataProjected.GetXaxis().GetBinLowEdge(1)
        maxRangeX = hMultDataProjected.GetXaxis().GetBinLowEdge(hMultDataProjected.GetNbinsX()+1)
        ROOT.gPad.DrawFrame(minRangeX, minRangeY*0.9, maxRangeX, maxRangeY*1.1, "All events;N_{PV};Counts")
        hMultDataProjected.Draw("same")
        hMultMCAllProjected.Draw("same")
        canvasDplusPrompt.cd(2)
        minRangeY = min(hMultDataCandsProjected.GetMinimum(), hMultMCDplusPromptCandsProjected.GetMinimum())
        maxRangeY = max(hMultDataCandsProjected.GetMaximum(), hMultMCDplusPromptCandsProjected.GetMaximum())
        minRangeX = hMultDataCandsProjected.GetXaxis().GetBinLowEdge(1)
        maxRangeX = hMultDataCandsProjected.GetXaxis().GetBinLowEdge(hMultDataCandsProjected.GetNbinsX()+1)
        ROOT.gPad.DrawFrame(minRangeX, minRangeY*0.9, maxRangeX, maxRangeY*1.1, "Events with Dplus cand;N_{PV};Counts")
        hMultDataCandsProjected.Draw("same")
        hMultMCDplusPromptCandsProjected.Draw("same")
        canvasDplusPrompt.cd(3)
        minRangeY = min(hMultDataCandsInSignalRegionDplusProjected.GetMinimum(), hMultMCDplusPromptCandsInSignalRegionProjected.GetMinimum())
        maxRangeY = max(hMultDataCandsInSignalRegionDplusProjected.GetMaximum(), hMultMCDplusPromptCandsInSignalRegionProjected.GetMaximum())
        minRangeX = hMultDataCandsInSignalRegionDplusProjected.GetXaxis().GetBinLowEdge(1)
        maxRangeX = hMultDataCandsInSignalRegionDplusProjected.GetXaxis().GetBinLowEdge(hMultDataCandsInSignalRegionDplusProjected.GetNbinsX()+1)
        ROOT.gPad.DrawFrame(minRangeX, minRangeY*0.9, maxRangeX, maxRangeY*1.1, "Events with Dplus cand in mass region;N_{PV};Counts")
        hMultDataCandsInSignalRegionDplusProjected.Draw("same")
        hMultMCDplusPromptCandsInSignalRegionProjected.Draw("same")
        canvasDplusPrompt.cd(4)
        hWeightAll.Draw()
        canvasDplusPrompt.cd(5)
        hWeightDplusPromptCands.Draw()
        canvasDplusPrompt.cd(6)
        hWeightDplusPromptCandsInSignalRegion.Draw()
        canvasDplusPrompt.Write()
        
        canvasDplusNonPrompt = ROOT.TCanvas(f"canvasDplusNonPrompt_{cent_min}_{cent_max}", f"canvasDplusNonPrompt_{cent_min}_{cent_max}", 800, 600)
        canvasDplusNonPrompt.Divide(3,2)
        canvasDplusNonPrompt.cd(1)
        minRangeY = min(hMultDataProjected.GetMinimum(), hMultMCAllProjected.GetMinimum())
        maxRangeY = max(hMultDataProjected.GetMaximum(), hMultMCAllProjected.GetMaximum())
        minRangeX = hMultDataProjected.GetXaxis().GetBinLowEdge(1)
        maxRangeX = hMultDataProjected.GetXaxis().GetBinLowEdge(hMultDataProjected.GetNbinsX()+1)
        ROOT.gPad.DrawFrame(minRangeX, minRangeY*0.9, maxRangeX, maxRangeY*1.1, "All events;N_{PV};Counts")
        hMultDataProjected.Draw("same")
        hMultMCAllProjected.Draw("same")
        canvasDplusNonPrompt.cd(2)
        minRangeY = min(hMultDataCandsProjected.GetMinimum(), hMultMCDplusNonPromptCandsProjected.GetMinimum())
        maxRangeY = max(hMultDataCandsProjected.GetMaximum(), hMultMCDplusNonPromptCandsProjected.GetMaximum())
        minRangeX = hMultDataCandsProjected.GetXaxis().GetBinLowEdge(1)
        maxRangeX = hMultDataCandsProjected.GetXaxis().GetBinLowEdge(hMultDataCandsProjected.GetNbinsX()+1)
        ROOT.gPad.DrawFrame(minRangeX, minRangeY*0.9, maxRangeX, maxRangeY*1.1, "Events with Dplus cand;N_{PV};Counts")
        hMultDataCandsProjected.Draw("same")
        hMultMCDplusNonPromptCandsProjected.Draw("same")
        canvasDplusNonPrompt.cd(3)
        minRangeY = min(hMultDataCandsInSignalRegionDplusProjected.GetMinimum(), hMultMCDplusNonPromptCandsInSignalRegionProjected.GetMinimum())
        maxRangeY = max(hMultDataCandsInSignalRegionDplusProjected.GetMaximum(), hMultMCDplusNonPromptCandsInSignalRegionProjected.GetMaximum())
        minRangeX = hMultDataCandsInSignalRegionDplusProjected.GetXaxis().GetBinLowEdge(1)
        maxRangeX = hMultDataCandsInSignalRegionDplusProjected.GetXaxis().GetBinLowEdge(hMultDataCandsInSignalRegionDplusProjected.GetNbinsX()+1)
        ROOT.gPad.DrawFrame(minRangeX, minRangeY*0.9, maxRangeX, maxRangeY*1.1, "Events with Dplus cand in mass region;N_{PV};Counts")
        hMultDataCandsInSignalRegionDplusProjected.Draw("same")
        hMultMCDplusNonPromptCandsInSignalRegionProjected.Draw("same")
        canvasDplusNonPrompt.cd(4)
        hWeightAll.Draw()
        canvasDplusNonPrompt.cd(5)
        hWeightDplusNonPromptCands.Draw()
        canvasDplusNonPrompt.cd(6)
        hWeightDplusNonPromptCandsInSignalRegion.Draw()
        canvasDplusNonPrompt.Write()
        
        hWeightAll.Write()
        hWeightDsPromptCands.Write()
        hWeightDsPromptCandsInSignalRegion.Write()
        hWeightDsNonPromptCands.Write()
        hWeightDsNonPromptCandsInSignalRegion.Write()   
        hWeightDplusPromptCands.Write()
        hWeightDplusPromptCandsInSignalRegion.Write()
        hWeightDplusNonPromptCands.Write()
        hWeightDplusNonPromptCandsInSignalRegion.Write()

    hMultMCAllProjected.Write()
    hMultMCDsPromptCandsProjected.Write()
    hMultMCDsPromptCandsInSignalRegionProjected.Write()
    hMultMCDsNonPromptCandsProjected.Write()
    hMultMCDsNonPromptCandsInSignalRegionProjected.Write()
    hMultMCDplusPromptCandsProjected.Write()
    hMultMCDplusPromptCandsInSignalRegionProjected.Write()
    hMultMCDplusNonPromptCandsProjected.Write()
    hMultMCDplusNonPromptCandsInSignalRegionProjected.Write()




    outfile.Close()



