import ROOT 

infileAfterBugFix = ROOT.TFile.Open("/home/fchinu/Run3/Ds_pp_13TeV/Efficiency/Efficiencies_LHC24d3a.root")
infileBeforeBugFix = ROOT.TFile.Open("/home/fchinu/Run3/Ds_pp_13TeV/Efficiency/Efficiencies_LHC24d3a_bug.root")

EffDsPromptAfterBugFix = infileAfterBugFix.Get("Eff_DsPrompt")
EffDsPromptBeforeBugFix = infileBeforeBugFix.Get("Eff_DsPrompt")
EffDsFDAfterBugFix = infileAfterBugFix.Get("Eff_DsFD")
EffDsFDBeforeBugFix = infileBeforeBugFix.Get("Eff_DsFD")
EffDplusPromptAfterBugFix = infileAfterBugFix.Get("Eff_DplusPrompt")
EffDplusPromptBeforeBugFix = infileBeforeBugFix.Get("Eff_DplusPrompt")
EffDplusFDAfterBugFix = infileAfterBugFix.Get("Eff_DplusFD")
EffDplusFDBeforeBugFix = infileBeforeBugFix.Get("Eff_DplusFD")

EffDsPromptAfterBugFix.SetDirectory(0)
EffDsPromptBeforeBugFix.SetDirectory(0)
EffDsFDAfterBugFix.SetDirectory(0)
EffDsFDBeforeBugFix.SetDirectory(0)
EffDplusPromptAfterBugFix.SetDirectory(0)
EffDplusPromptBeforeBugFix.SetDirectory(0)
EffDplusFDAfterBugFix.SetDirectory(0)
EffDplusFDBeforeBugFix.SetDirectory(0)

infileAfterBugFix.Close()
infileBeforeBugFix.Close()

canvas = ROOT.TCanvas("canvas", "canvas", 800, 600)
canvas.DrawFrame(0, 0.5, 24, 3.5, ";#it{p}_{T} (GeV/#it{c});Efficiency After Bug Fix / Efficiency Before Bug Fix")
EffDsPromptAfterBugFix.Divide(EffDsPromptAfterBugFix, EffDsPromptBeforeBugFix, 1, 1, "b")
EffDsPromptAfterBugFix.SetMarkerColor(ROOT.kRed)
EffDsPromptAfterBugFix.SetMarkerStyle(ROOT.kFullCircle)
EffDsPromptAfterBugFix.SetLineColor(ROOT.kRed)
EffDsPromptAfterBugFix.Draw("same")
EffDsFDAfterBugFix.Divide(EffDsFDAfterBugFix, EffDsFDBeforeBugFix, 1, 1, "b")
EffDsFDAfterBugFix.SetMarkerColor(ROOT.kBlack)
EffDsFDAfterBugFix.SetMarkerStyle(ROOT.kFullCircle)
EffDsFDAfterBugFix.SetLineColor(ROOT.kBlack)
EffDsFDAfterBugFix.Draw("same")
EffDplusPromptAfterBugFix.Divide(EffDplusPromptAfterBugFix, EffDplusPromptBeforeBugFix, 1, 1, "b")
EffDplusPromptAfterBugFix.SetMarkerColor(ROOT.kBlue)
EffDplusPromptAfterBugFix.SetMarkerStyle(ROOT.kFullCircle)
EffDplusPromptAfterBugFix.SetLineColor(ROOT.kBlue)
EffDplusPromptAfterBugFix.Draw("same")
EffDplusFDAfterBugFix.Divide(EffDplusFDAfterBugFix, EffDplusFDBeforeBugFix, 1, 1, "b")
EffDplusFDAfterBugFix.SetMarkerColor(ROOT.kOrange-3)
EffDplusFDAfterBugFix.SetMarkerStyle(ROOT.kFullCircle)
EffDplusFDAfterBugFix.SetLineColor(ROOT.kOrange-3)
EffDplusFDAfterBugFix.Draw("same")

leg = ROOT.TLegend(0.2, 0.2, 0.5, 0.4)
leg.SetBorderSize(0)
leg.SetFillStyle(0)
leg.AddEntry(EffDsPromptAfterBugFix, "Ds Prompt", "pl")
leg.AddEntry(EffDsFDAfterBugFix, "Ds FD", "pl")
leg.AddEntry(EffDplusPromptAfterBugFix, "Dplus Prompt", "pl")
leg.AddEntry(EffDplusFDAfterBugFix, "Dplus FD", "pl")
leg.Draw()

canvas.SaveAs("/home/fchinu/Run3/Ds_pp_13TeV/Efficiency/EfficiencyComparisonBeforeAfterFix.png")

