import ROOT

# Ds MC
fileDs = ROOT.TFile.Open("/home/fchinu/Run3/Ds_pp_13TeV/Projections_RawYields/MC/RawYields_DsMC.root")
histoSigmaDs = fileDs.Get("hRawYieldsSigma")
histoSigmaDs.SetDirectory(0)
fileDs.Close()
histoSigmaDs.SetName("hSigmaDsMC")
histoSigmaDs.Scale(1000)
histoSigmaDs.SetMarkerStyle(ROOT.kFullCircle)
histoSigmaDs.SetMarkerColor(ROOT.kRed)
histoSigmaDs.SetLineColor(ROOT.kRed)

# Dplus MC
fileDplus = ROOT.TFile.Open("/home/fchinu/Run3/Ds_pp_13TeV/Projections_RawYields/MC/RawYields_DplusMC.root")
histoSigmaDplus = fileDplus.Get("hRawYieldsSigma")
histoSigmaDplus.SetDirectory(0)
fileDplus.Close()
histoSigmaDplus.SetName("hSigmaDplusMC")
histoSigmaDplus.Scale(1000)
histoSigmaDplus.SetMarkerStyle(ROOT.kFullSquare)
histoSigmaDplus.SetMarkerColor(ROOT.kBlue)
histoSigmaDplus.SetLineColor(ROOT.kBlue)

# Ds and Dplus data
fileData = ROOT.TFile.Open("/home/fchinu/Run3/Ds_pp_13TeV/Projections_RawYields/Data/RawYields_Data.root")
histoSigmaDsData = fileData.Get("hRawYieldsSigma")
histoSigmaDsData.SetDirectory(0)
histoSigmaDplusData = fileData.Get("hRawYieldsSigmaSecondPeak")
histoSigmaDplusData.SetDirectory(0)
fileData.Close()

histoSigmaDsData.SetName("hSigmaDsData")
histoSigmaDsData.Scale(1000)
histoSigmaDsData.SetMarkerStyle(ROOT.kOpenCircle)
histoSigmaDsData.SetMarkerColor(ROOT.kRed)
histoSigmaDsData.SetLineColor(ROOT.kRed)

histoSigmaDplusData.SetName("hSigmaDplusData")
histoSigmaDplusData.Scale(1000)
histoSigmaDplusData.SetMarkerStyle(ROOT.kOpenSquare)
histoSigmaDplusData.SetMarkerColor(ROOT.kBlue)
histoSigmaDplusData.SetLineColor(ROOT.kBlue)

# Compare widths and ratios
cSigmaDs = ROOT.TCanvas("cSigmaDs", "cSigmaDs", 800, 600)
cSigmaDs.DrawFrame(1.8, 0., 24, 50, "#sigma_{D_{s}} [MeV/c^{2}]; #it{p}_{T} [GeV/#it{c}]; #sigma_{D_{s}} [MeV/c^{2}]")
histoSigmaDs.Draw("same")
histoSigmaDsData.Draw("same")

legDs = ROOT.TLegend(0.6, 0.75, 0.9, 0.85)
legDs.AddEntry(histoSigmaDs, "MC #sigma_{D_{s}}", "lp")
legDs.AddEntry(histoSigmaDsData, "Data #sigma_{D_{s}}", "lp")
legDs.SetTextSize(0.04)
legDs.SetFillStyle(0)
legDs.SetBorderSize(0)
legDs.Draw()

cSigmaDplus = ROOT.TCanvas("cSigmaDplus", "cSigmaDplus", 800, 600)
cSigmaDplus.DrawFrame(1.8, 0., 24, 50, "#sigma_{D^{+}} [MeV/c^{2}]; #it{p}_{T} [GeV/#it{c}]; #sigma_{D^{+}} [MeV/c^{2}]")
histoSigmaDplus.Draw("same")
histoSigmaDplusData.Draw("same")

legDplus = ROOT.TLegend(0.6, 0.75, 0.9, 0.85)
legDplus.AddEntry(histoSigmaDplus, "MC #sigma_{D^{+}}", "lp")
legDplus.AddEntry(histoSigmaDplusData, "Data #sigma_{D^{+}}", "lp")
legDplus.SetTextSize(0.04)
legDplus.SetFillStyle(0)
legDplus.SetBorderSize(0)
legDplus.Draw()

histoRatio = histoSigmaDs.Clone("hSigmaDsOverDplusMC")
histoRatio.Divide(histoSigmaDplus)
histoRatio.SetMarkerStyle(ROOT.kFullCircle)
histoRatio.SetMarkerColor(ROOT.kRed)

histoRatioData = histoSigmaDsData.Clone("hSigmaDsOverDplusData")
histoRatioData.Divide(histoSigmaDplusData)
histoRatioData.SetMarkerStyle(ROOT.kOpenCircle)
histoRatioData.SetMarkerColor(ROOT.kRed)

cRatio = ROOT.TCanvas("cRatio", "cRatio", 800, 600)
cRatio.DrawFrame(1.8, 0., 24, 2.5, "#sigma_{D_{s}}/#sigma_{D^{+}}; #it{p}_{T} [GeV/#it{c}]; #sigma_{D_{s}}/#sigma_{D^{+}}")
histoRatio.Draw("same")
histoRatioData.Draw("same")

legRatio = ROOT.TLegend(0.6, 0.75, 0.9, 0.85)
legRatio.AddEntry(histoRatio, "MC #sigma_{D_{s}}/#sigma_{D^{+}}", "lp")
legRatio.AddEntry(histoRatioData, "Data #sigma_{D_{s}}/#sigma_{D^{+}}", "lp")
legRatio.SetTextSize(0.04)
legRatio.SetFillStyle(0)
legRatio.SetBorderSize(0)
legRatio.Draw()

outputFile = ROOT.TFile.Open("/home/fchinu/Run3/Ds_pp_13TeV/Projections_RawYields/SigmaDsOverDplusMC.root", "RECREATE")
outputFile.cd()
histoSigmaDs.Write()
histoSigmaDplus.Write()
histoSigmaDsData.Write()
histoSigmaDplusData.Write()
histoRatio.Write()
histoRatioData.Write()
cSigmaDs.Write()
cSigmaDplus.Write()
cRatio.Write()
outputFile.Close()

cSigmaDs.SaveAs("/home/fchinu/Run3/Ds_pp_13TeV/Projections_RawYields/SigmaDsMC.png")
cSigmaDplus.SaveAs("/home/fchinu/Run3/Ds_pp_13TeV/Projections_RawYields/SigmaDplusMC.png")
cRatio.SaveAs("/home/fchinu/Run3/Ds_pp_13TeV/Projections_RawYields/SigmaDsOverDplusMC.png")
