inputs:
  data: "/home/fchinu/Run3/Ds_Dp_ratio_PbPb/Projections_RawYields/data/norm_vars/Projections/projections.root"
  mc: 
    ds: Projections_RawYields/Data/LHC22o_pass7/VsMult/Projections_MC.root
    dplus: Projections_RawYields/Data/LHC22o_pass7/VsMult/Projections_MC.root
  cutset: "/home/fchinu/Run3/Ds_Dp_ratio_PbPb/Projections_RawYields/data/norm_vars/Projections/cutset.yml"

max_workers: 10

zfit_cpus:
  intra: 20
  inter: 20

fit_configs:
  # below one per pT bin
  mass:
    mins: [1.75, 1.75, 1.75, 1.73, 1.73, 1.73]
    maxs: [2.1, 2.1, 2.1, 2.15, 2.15, 2.15]
  rebin: [4, 4, 4, 4, 4, 4]
  signal:
    signal_funcs: [["gaussian", "gaussian"], ["gaussian", "gaussian"], ["gaussian", "gaussian"],
      ["gaussian", "gaussian"], ["gaussian", "gaussian"], ["gaussian", "gaussian"]]
    par_init_limit:
      - sigma:
          init: [0.001, 0.01, 0.01, 0.02, 0.02, 0.02]
          min: [0.001, 0.001, 0.001, 0.001, 0.001, 0.001]
          max: [0.013, 0.013, 0.02, 0.03, 0.04, 0.04]
          fix: [false, false, false, false, false, false]
        alpha:
          init: [1.95, 1.74, 1.64, 1.66, 1.63, 1.84]
          min: [0., 0., 0., 0., 0.5, 0.75]
          max: [5., 5., 5., 5., 5., 5.]
          fix: [true, true, true, true, true, true]
        n:
          init: [3.64, 3.72, 4.28, 3.94, 4.44, 3.25]
          min: [3, 3, 3, 3, 3, 3]
          max: [100., 100., 100., 100., 100., 100.]
          fix: [true, true, true, true, true, true]
      - sigma:
          init: [0.001, 0.01, 0.015, 0.02, 0.02, 0.02]
          min: [0.001, 0.001, 0.001, 0.001, 0.001, 0.001]
          max: [0.013, 0.013, 0.025, 0.03, 0.04, 0.04]
          fix: [false, false, false, false, false, false]
        alpha:
          init: [1.80, 1.73, 1.66, 1.63, 1.63, 1.73]
          min: [0., 0., 0., 0., 0.5, 0.75]
          max: [5., 5., 5., 5., 5., 5.]
          fix: [true, true, true, true, true, true]
        n:
          init: [4.10, 3.77, 4.14, 4.26, 3.98, 3.95]
          min: [3, 3, 3, 3, 3, 3]
          max: [100., 100., 100., 100., 100., 100.]
          fix: [true, true, true, true, true, true]

    fix_sigma_to_mb: [false, false, false, false, false, false]
    fix_ds_sigma: [false, false, false, false, false, false]
    ds_sigma: # value, list or path to root_file. If null or empty, fit MC and then use that sigma
    fix_dplus_sigma: [false, false, false, false, false, false]
    dplus_sigma: [] # value, list or path to root_file. If null or empty, fit MC and then use that sigma
    fix_sigma_dplus_to_ds: [false, false, false, false, false, false]
    ratio_sigma_dplus_to_ds: [0.9, 0.9, 0.9, 0.9, 0.9, 0.9] # value, list or path to root_file. If null or empty, set dplus sigma to that of ds. Otherwise, set to ds sigma * value
  bkg:
    bkg_funcs: [['chebpol2'], ['chebpol2'], ['chebpol2'], ['chebpol2'], ['chebpol2'], ['chebpol2']]
    use_bkg_templ: [false, false, false, false, false, false]
    templ_norm:
      fix_to_mb: [true, true, true, true, true, true]
      fix_to_file_name: null # set to null if no file is needed
      hist_name: h_corr_bkg_over_dplus_signal_0_100  # can use also pt_min, pt_max, cent_min, cent_max to format name. pt variables are multiplied by 10 to avoid floating point issues
      fix_with_br: [true, true, true, true, true, true]
      backgrounds:
      - name: $\mathrm{D^{+}}\rightarrow K^{-}\pi^{+}\pi^{+}$
        file_norm: /home/fchinu/Run3/Ds_pp_13TeV/Projections_RawYields/MC/VsMult/LHC24h1/w_bdt/dplus_bkg.root # with BDT selections (for normalisation)
        norm_hist_name: 'h_mass_{pt_min}_{pt_max}'
        template_file: /home/fchinu/Run3/Ds_pp_13TeV/Projections_RawYields/MC/VsMult/LHC24h1/no_bdt/dplus_corr_bkg_template.root
        template_hist_name: 'h_mass_{pt_min}_{pt_max}' # can use also pt_min, pt_max, cent_min, cent_max to format name. pt variables are multiplied by 10 to avoid floating point issues
        br:
          pdg: 0.0938 # K pi pi
          simulations: 0.4853 # 0.4263 + 0.059 (K pi pi + K0* pi)
      # - name: $\mathrm{\Lambda_{c}^{+}}\rightarrow pK^{-}\pi^{+}$
      #   file_norm: /home/fchinu/Run3/Ds_pp_13TeV/Projections_RawYields/MC/VsMult/LHC24g5_lc/w_bdt/lc.root # with BDT selections (for normalisation)
      #   norm_hist_name: 'h_mass_{pt_min}_{pt_max}'
      #   template_file: /home/fchinu/Run3/Ds_pp_13TeV/Projections_RawYields/MC/VsMult/LHC24g5_lc/no_bdt/lc_corr_bkg_template.root
      #   template_hist_name: 'h_mass_{pt_min}_{pt_max}' # can use also pt_min, pt_max, cent_min, cent_max to format name. pt variables are multiplied by 10 to avoid floating point issues
      #   br:
      #     pdg: 0.0624 # p K pi
      #     simulations: 0.3388
      signal:
        file_norm: /home/fchinu/Run3/Ds_pp_13TeV/Projections_RawYields/MC/VsMult/LHC24h1/w_bdt/dplus.root # str or list of str
        hist_name: 'h_mass_{pt_min}_{pt_max}' # can use also pt_min, pt_max, cent_min, cent_max to format name. pt variables are multiplied by 10 to avoid floating point issues

        br:
          pdg: 0.00269
          simulations: 0.4263
    


output:
  directory: "/home/fchinu/Run3/Ds_Dp_ratio_PbPb/Projections_RawYields/data/norm_vars/RawYields"
  suffix: ""
  save_all_fits: true
  formats: ["png", "pdf"]
