var_key: ['ml_output_fd']
var_tag: ['outFD']
step_variation:
  - "1.0": 0.05
    "2.0": 0.05
    "4.0": 0.05
    "6.0": 0.05
    "8.0": 0.04
    "12.0": 0.04
num_step_pos: 5
num_step_pos_half_step: 0
num_step_neg: 0
num_step_neg_half_step: 0
edge_to_vary: ['min']

in_dir: "/home/fchinu/Run3/Ds_pp_13TeV/FD_Fraction/data_driven/OO/"
cut_file_central: "cutset.yml"
out_dir: "/home/fchinu/Run3/Ds_pp_13TeV/FD_Fraction/data_driven/OO/configs/cutsets/"
out_file_tag: "cutset_ML_FD"
