inputs:
  names: [
    # /home/fchinu/Run3/Ds_pp_13TeV/Datasets/Ds_pp_run3_ml/Data/Train279067/AnalysisResults_LHC22o_pass7.root,
    /home/fchinu/Run3/Ds_pp_13TeV/Datasets/Ds_pp_run3_ml/Data/Train290606/AnalysisResults_LHC23_pass4_0.root,
  ] # string or list of strings
  sparses: hf-task-ds/Data/hSparseMass
  event_histogram: bc-selection-task/hCounterTVXafterBCcuts

  cutset: /home/fchinu/Run3/Ds_pp_13TeV/Projections_RawYields/configs/cutset_pp13TeV_multiplicity.yml

max_workers: 10

output:
  directory: /home/fchinu/Run3/Ds_pp_13TeV/FD_Fraction/data_driven/VsMult/Projections_RawYields
  file_names: [
    # data_LHC22.root,
    data_LHC23_0.root,
  ]

