import ROOT 
import numpy as np

TransparentBlue = ROOT.TColor.GetFreeColorIndex()
cTransparentBlue = ROOT.TColor(TransparentBlue, 79./255, 123./255, 161./255, 'TransparentBlue', 1.0)

# LHCb comparison

ratioFileName = '/home/fchinu/Run3/Ds_pp_13TeV/Ratios/DsOverDplus_LHC24d3a.root'
systFileNameRawYields = '/home/fchinu/Run3/Ds_pp_13TeV/Systematics/RawYields/SystUncertainties.root'
systFileNameBDT = "/home/fchinu/Run3/Ds_pp_13TeV/Systematics/BDT/output/BDT_syst.root"
systFileNameFD = "/home/fchinu/Run3/Ds_pp_13TeV/Systematics/FD_Fraction/FDSystematic.root"
systFileNameTopo = "/home/fchinu/Run3/Ds_pp_13TeV/Systematics/Tracking/Results/SystUncertainty.root"
LHCbFileName = '/home/fchinu/Run3/Ds_pp_13TeV/Ratios/pp_data/ds_over_dplus_lhcb.root'

ratioFile = ROOT.TFile(ratioFileName)
hRatio = ratioFile.Get('hRatio')
hRatio.SetDirectory(0)
ratioFile.Close()

systFileRawYields = ROOT.TFile(systFileNameRawYields)
hSystRawYields = systFileRawYields.Get('hSyst')
hSystRawYields.SetDirectory(0)
systFileRawYields.Close()

systFileBDT = ROOT.TFile(systFileNameBDT)
hSystBDT = systFileBDT.Get('hSyst')
hSystBDT.SetDirectory(0)
systFileBDT.Close()

systFileFD = ROOT.TFile(systFileNameFD)
hSystFD = systFileFD.Get('hSyst')
hSystFD.SetDirectory(0)
systFileFD.Close()

systFileTopo = ROOT.TFile(systFileNameTopo)
hSystTopo = systFileTopo.Get('hSyst')
hSystTopo.SetDirectory(0)
systFileTopo.Close()

gSyst = ROOT.TGraphErrors(hSystRawYields)

for iPt in range(gSyst.GetN()):
    unc = np.sqrt(hSystRawYields.GetBinContent(iPt+1)**2 + hSystBDT.GetBinContent(iPt+1)**2 + hSystFD.GetBinContent(iPt+1)**2 + hSystTopo.GetBinContent(iPt+1)**2)
    gSyst.SetPointError(iPt, 0.2, unc*hRatio.GetBinContent(iPt+1))
    gSyst.SetPointY(iPt, hRatio.GetBinContent(iPt+1))

LHCbFile = ROOT.TFile(LHCbFileName)
hLHCb_20_25 = LHCbFile.Get('h_ds_over_dp_rap0')
hLHCb_20_25.SetDirectory(0)
hLHCb_25_30 = LHCbFile.Get('h_ds_over_dp_rap1')
hLHCb_25_30.SetDirectory(0)
hLHCb_30_35 = LHCbFile.Get('h_ds_over_dp_rap2')
hLHCb_30_35.SetDirectory(0)
hLHCb_35_40 = LHCbFile.Get('h_ds_over_dp_rap3')
hLHCb_35_40.SetDirectory(0)
hLHCb_40_45 = LHCbFile.Get('h_ds_over_dp_rap4')
hLHCb_40_45.SetDirectory(0)
gLHCb_20_25 = LHCbFile.Get('gsys_ds_over_dp_rap0')
gLHCb_25_30 = LHCbFile.Get('gsys_ds_over_dp_rap1')
gLHCb_30_35 = LHCbFile.Get('gsys_ds_over_dp_rap2')
gLHCb_35_40 = LHCbFile.Get('gsys_ds_over_dp_rap3')
gLHCb_40_45 = LHCbFile.Get('gsys_ds_over_dp_rap4')
LHCbFile.Close()

# Set style
hRatio.SetLineColor(ROOT.kRed)
hRatio.SetMarkerColor(ROOT.kRed)
hRatio.SetMarkerStyle(ROOT.kFullCircle)
hRatio.SetMarkerSize(1.5)
hRatio.SetLineWidth(2)

hRatioBorder = hRatio.Clone('hRatioBorder')
hRatioBorder.SetLineColor(ROOT.kRed)
hRatioBorder.SetMarkerColor(ROOT.kBlack)
hRatioBorder.SetMarkerStyle(53)
hRatioBorder.SetLineWidth(3)

gSyst.SetLineColor(ROOT.kRed)
gSyst.SetMarkerColor(ROOT.kRed)
gSyst.SetMarkerStyle(ROOT.kFullCircle)
gSyst.SetMarkerSize(1.5)
gSyst.SetLineWidth(2)
gSyst.SetFillStyle(0)

hLHCb_20_25.SetLineColor(ROOT.kAzure+7)
hLHCb_20_25.SetMarkerColor(ROOT.kAzure+7)
hLHCb_20_25.SetMarkerStyle(ROOT.kFullSquare)
hLHCb_20_25.SetMarkerSize(1.5)
hLHCb_20_25.SetLineWidth(2)

hLHCb_20_25Border = hLHCb_20_25.Clone('hLHCb_20_25Border')
hLHCb_20_25Border.SetLineColor(ROOT.kAzure+7)
hLHCb_20_25Border.SetMarkerColor(ROOT.kBlack)
hLHCb_20_25Border.SetMarkerStyle(54)
hLHCb_20_25Border.SetLineWidth(3)

gLHCb_20_25.SetLineColor(ROOT.kAzure+7)
gLHCb_20_25.SetFillStyle(0)
gLHCb_20_25.SetLineWidth(2)
for iPt in range(gLHCb_20_25.GetN()):
    gLHCb_20_25.SetPointEXhigh(iPt, 0.2)
    gLHCb_20_25.SetPointEXlow(iPt, 0.2)

hLHCb_25_30.SetLineColor(ROOT.kGreen-2)
hLHCb_25_30.SetMarkerColor(ROOT.kGreen-2)
hLHCb_25_30.SetMarkerStyle(ROOT.kFullCross)
hLHCb_25_30.SetMarkerSize(1.5)
hLHCb_25_30.SetLineWidth(2)

hLHCb_25_30Border = hLHCb_25_30.Clone('hLHCb_25_30Border')
hLHCb_25_30Border.SetLineColor(ROOT.kGreen-2)
hLHCb_25_30Border.SetMarkerColor(ROOT.kBlack)
hLHCb_25_30Border.SetMarkerStyle(57)
hLHCb_25_30Border.SetLineWidth(3)

gLHCb_25_30.SetLineColor(ROOT.kGreen-2)
gLHCb_25_30.SetFillStyle(0)
gLHCb_25_30.SetLineWidth(2)
for iPt in range(gLHCb_25_30.GetN()):
    gLHCb_25_30.SetPointEXhigh(iPt, 0.2)
    gLHCb_25_30.SetPointEXlow(iPt, 0.2)

hLHCb_30_35.SetLineColor(ROOT.kAzure+7)
hLHCb_30_35.SetMarkerColor(ROOT.kAzure+7)
hLHCb_30_35.SetMarkerStyle(ROOT.kFullSquare)
hLHCb_30_35.SetMarkerSize(1.5)
hLHCb_30_35.SetLineWidth(2)

hLHCb_30_35Border = hLHCb_30_35.Clone('hLHCb_30_35Border')
hLHCb_30_35Border.SetLineColor(ROOT.kAzure+7)
hLHCb_30_35Border.SetMarkerColor(ROOT.kBlack)
hLHCb_30_35Border.SetMarkerStyle(54)
hLHCb_30_35Border.SetLineWidth(3)

gLHCb_30_35.SetLineColor(ROOT.kAzure+7)
gLHCb_30_35.SetFillStyle(0)
gLHCb_30_35.SetLineWidth(2)
for iPt in range(gLHCb_30_35.GetN()):
    gLHCb_30_35.SetPointEXhigh(iPt, 0.2)
    gLHCb_30_35.SetPointEXlow(iPt, 0.2)

hLHCb_35_40.SetLineColor(ROOT.kGreen-2)
hLHCb_35_40.SetMarkerColor(ROOT.kGreen-2)
hLHCb_35_40.SetMarkerStyle(ROOT.kFullCross)
hLHCb_35_40.SetMarkerSize(1.5)
hLHCb_35_40.SetLineWidth(2)

hLHCb_35_40Border = hLHCb_35_40.Clone('hLHCb_35_40Border')
hLHCb_35_40Border.SetLineColor(ROOT.kGreen-2)
hLHCb_35_40Border.SetMarkerColor(ROOT.kBlack)
hLHCb_35_40Border.SetMarkerStyle(57)
hLHCb_35_40Border.SetLineWidth(3)

gLHCb_35_40.SetLineColor(ROOT.kGreen-2)
gLHCb_35_40.SetFillStyle(0)
gLHCb_35_40.SetLineWidth(2)
for iPt in range(gLHCb_35_40.GetN()):
    gLHCb_35_40.SetPointEXhigh(iPt, 0.2)
    gLHCb_35_40.SetPointEXlow(iPt, 0.2)

hLHCb_40_45.SetLineColor(ROOT.kOrange-3)
hLHCb_40_45.SetMarkerColor(ROOT.kOrange-3)
hLHCb_40_45.SetMarkerStyle(ROOT.kFullCross)
hLHCb_40_45.SetMarkerSize(1.5)
hLHCb_40_45.SetLineWidth(2)

hLHCb_40_45Border = hLHCb_40_45.Clone('hLHCb_40_45Border')
hLHCb_40_45Border.SetLineColor(ROOT.kOrange-3)
hLHCb_40_45Border.SetMarkerColor(ROOT.kBlack)
hLHCb_40_45Border.SetMarkerStyle(57)
hLHCb_40_45Border.SetLineWidth(3)

gLHCb_40_45.SetLineColor(ROOT.kOrange-3)
gLHCb_40_45.SetFillStyle(0)
gLHCb_40_45.SetLineWidth(2)
for iPt in range(gLHCb_40_45.GetN()):
    gLHCb_40_45.SetPointEXhigh(iPt, 0.2)
    gLHCb_40_45.SetPointEXlow(iPt, 0.2)

canvas = ROOT.TCanvas('canvas', 'canvas', 800, 800)
ROOT.gPad.SetLeftMargin(0.12)
ROOT.gPad.SetRightMargin(0.04)
ROOT.gPad.SetTopMargin(0.05)
ROOT.gPad.SetBottomMargin(0.1)

hFrame = canvas.DrawFrame(0, 0, 24, 1., ';#it{p}_{T} (Ge#kern[-0.05]{V}/#it{c});D_{s}^{+}/D^{+}')
hFrame.GetXaxis().SetTitleOffset(1.05)
hFrame.GetYaxis().SetTitleOffset(1.2)
hFrame.GetXaxis().SetTitleSize(0.043)
hFrame.GetYaxis().SetTitleSize(0.043)
hFrame.GetXaxis().SetLabelSize(0.04)
hFrame.GetYaxis().SetLabelSize(0.04)
ROOT.gPad.SetTickx(1)
ROOT.gPad.SetTicky(1)
gLHCb_20_25.Draw('5 same')
gLHCb_25_30.Draw('5 same')
gSyst.Draw('5 same')
hLHCb_20_25.Draw('p same')
hLHCb_20_25Border.Draw('p same')
hLHCb_25_30.Draw('p same')
hLHCb_25_30Border.Draw('p same')
hRatio.Draw('p same')
hRatioBorder.Draw('p same')
canvas.Update()

textALICE = ROOT.TLatex(0.15, 0.88, 'ALICE Preliminary')
textALICE.SetNDC()
textALICE.SetTextFont(42)
textALICE.SetTextSize(0.05)
textALICE.Draw()

textpp = ROOT.TLatex(0.155, 0.84, 'pp collisions')
textpp.SetNDC()
textpp.SetTextFont(42)
textpp.SetTextSize(0.04)
textpp.Draw()

texty = ROOT.TLatex(0.15, 0.79, '#sqrt{#it{s}} = 13.6 Te#kern[-0.05]{V}')
texty.SetNDC()
texty.SetTextFont(42)
texty.SetTextSize(0.04)
texty.Draw()

textDsDecay = ROOT.TLatex(0.155, 0.74, 'D_{s}^{+}#rightarrow #phi#pi^{+}#rightarrow K^{+}K^{#font[122]{-}}#pi^{+} ')
textDsDecay.SetNDC()
textDsDecay.SetTextFont(42)
textDsDecay.SetTextSize(0.035)
textDsDecay.Draw()

textDsDecayConj = ROOT.TLatex(0.155, 0.7, 'and charge conj.')
textDsDecayConj.SetNDC()
textDsDecayConj.SetTextFont(42)
textDsDecayConj.SetTextSize(0.035)
textDsDecayConj.Draw()

textEnergy = ROOT.TLatex(0.155, 0.85, '#sqrt{#it{s}} = 13.6 Te#kern[-0.05]{V}')
textEnergy.SetNDC()
textEnergy.SetTextFont(42)
textEnergy.SetTextSize(0.035)
#textEnergy.Draw()

textDecay = ROOT.TLatex(0.6, 0.88, 'D^{+}#rightarrow #phi#pi^{+}#rightarrow K^{+}K^{#font[122]{-}}#pi^{+} ')
textDecay.SetNDC()
textDecay.SetTextFont(42)
textDecay.SetTextSize(0.035)
textDecay.Draw()

textDecayConj = ROOT.TLatex(0.6, 0.84, 'and charge conj.')
textDecayConj.SetNDC()
textDecayConj.SetTextFont(42)
textDecayConj.SetTextSize(0.035)
textDecayConj.Draw()

textBR = ROOT.TLatex(0.6, 0.8, 'BR unc. (not shown): ^{#lower[5]{+3.7}}_{#lower[-0.2]{#font[122]{-}4.0}}#it{%} ')
textBR.SetNDC()
textBR.SetTextFont(42)
textBR.SetTextSize(0.03)
textBR.Draw()

Thislegend = ROOT.TLegend(0.6, 0.75, 0.8, 0.78)
Thislegend.SetBorderSize(0)
Thislegend.SetTextSize(0.0285)
Thislegend.SetFillStyle(0)
Thislegend.AddEntry(hRatio, '|#it{y}| < 0.5', 'lp')
Thislegend.Draw()

ThislegendBorder = ROOT.TLegend(0.6, 0.75, 0.8, 0.78)
ThislegendBorder.SetBorderSize(0)
ThislegendBorder.SetTextSize(0.0285)
ThislegendBorder.SetFillStyle(0)
ThislegendBorder.AddEntry(hRatioBorder, '|#it{y}| < 0.5', 'lp')
ThislegendBorder.Draw()

text = ROOT.TLatex(0.25, 0.35, 'D^{+}#rightarrow #pi^{+}K^{#font[122]{-}}#pi^{+}')
text.SetNDC()
text.SetTextFont(42)
text.SetTextSize(0.035)
text.Draw()

textConj = ROOT.TLatex(0.25, 0.31, 'and charge conj.')
textConj.SetNDC()
textConj.SetTextFont(42)
textConj.SetTextSize(0.035)
textConj.Draw()

textBRGoldenDplus = ROOT.TLatex(0.25, 0.27, 'BR unc. (not shown): 3.2#it{%}')
textBRGoldenDplus.SetNDC()
textBRGoldenDplus.SetTextFont(42)
textBRGoldenDplus.SetTextSize(0.03)
textBRGoldenDplus.Draw()

LegLHCbText = ROOT.TLatex(0.25, 0.23, 'LHCb, #sqrt{#it{s}} = 13 Te#kern[-0.05]{V}, JHEP 03 (2016) 159')
LegLHCbText.SetNDC()
LegLHCbText.SetTextFont(42)
LegLHCbText.SetTextSize(0.03)
LegLHCbText.Draw()

legLHCb = ROOT.TLegend(0.25, 0.13, 0.45, 0.21)
legLHCb.SetBorderSize(0)
legLHCb.SetTextSize(0.0285)
legLHCb.SetFillStyle(0)
legLHCb.AddEntry(hLHCb_20_25, '2.0 < #it{y} < 2.5', 'lp')
legLHCb.AddEntry(hLHCb_25_30, '2.5 < #it{y} < 3.0', 'lp')
legLHCb.Draw()

legLHCbBorder = ROOT.TLegend(0.25, 0.13, 0.45, 0.21)
legLHCbBorder.SetBorderSize(0)
legLHCbBorder.SetTextSize(0.0285)
legLHCbBorder.SetFillStyle(0)
legLHCbBorder.AddEntry(hLHCb_20_25Border, '2.0 < #it{y} < 2.5', 'lp')
legLHCbBorder.AddEntry(hLHCb_25_30Border, '2.5 < #it{y} < 3.0', 'lp')
legLHCbBorder.Draw()

ROOT.gPad.RedrawAxis()

canvas.SaveAs('/home/fchinu/Run3/Ds_pp_13TeV/Figures/Ratio/DsOverDplusComparisonLHCb.png')
canvas.SaveAs('/home/fchinu/Run3/Ds_pp_13TeV/Figures/Ratio/DsOverDplusComparisonLHCb.pdf')
canvas.SaveAs('/home/fchinu/Run3/Ds_pp_13TeV/Figures/Ratio/DsOverDplusComparisonLHCb.eps')


canvasHighRap = ROOT.TCanvas('canvasHighRap', 'canvasHighRap', 800, 800)
ROOT.gPad.SetLeftMargin(0.12)
ROOT.gPad.SetRightMargin(0.04)
ROOT.gPad.SetTopMargin(0.05)
ROOT.gPad.SetBottomMargin(0.1)

hFrame = canvasHighRap.DrawFrame(0, 0, 24, 1., ';#it{p}_{T} (Ge#kern[-0.05]{V}/#it{c});D_{s}^{+}/D^{+}')
hFrame.GetXaxis().SetTitleOffset(1.05)
hFrame.GetYaxis().SetTitleOffset(1.2)
hFrame.GetXaxis().SetTitleSize(0.043)
hFrame.GetYaxis().SetTitleSize(0.043)
hFrame.GetXaxis().SetLabelSize(0.04)
hFrame.GetYaxis().SetLabelSize(0.04)
ROOT.gPad.SetTickx(1)
ROOT.gPad.SetTicky(1)
gLHCb_30_35.Draw('5 same')
gLHCb_35_40.Draw('5 same')
gLHCb_40_45.Draw('5 same')
gSyst.Draw('5 same')
hLHCb_30_35.Draw('p same')
hLHCb_30_35Border.Draw('p same')
hLHCb_35_40.Draw('p same')
hLHCb_35_40Border.Draw('p same')
hLHCb_40_45.Draw('p same')
hLHCb_40_45Border.Draw('p same')
hRatio.Draw('p same')
hRatioBorder.Draw('p same')
canvasHighRap.Update()


textThesis = ROOT.TLatex(0.20, 0.88, 'This Thesis')
textThesis.SetNDC()
textThesis.SetTextFont(42)
textThesis.SetTextSize(0.05)
textThesis.Draw()

textpp2 = ROOT.TLatex(0.205, 0.84, 'pp collisions')
textpp2.SetNDC()
textpp2.SetTextFont(42)
textpp2.SetTextSize(0.04)
textpp2.Draw()

texty2 = ROOT.TLatex(0.20, 0.79, '#sqrt{#it{s}} = 13.6 Te#kern[-0.05]{V}')
texty2.SetNDC()
texty2.SetTextFont(42)
texty2.SetTextSize(0.04)
texty2.Draw()

textDsDecay2 = ROOT.TLatex(0.205, 0.74, 'D_{s}^{+}#rightarrow #phi#pi^{+}#rightarrow K^{+}K^{#font[122]{-}}#pi^{+} ')
textDsDecay2.SetNDC()
textDsDecay2.SetTextFont(42)
textDsDecay2.SetTextSize(0.035)
textDsDecay2.Draw()

textDsDecayConj2 = ROOT.TLatex(0.205, 0.7, 'and charge conj.')
textDsDecayConj2.SetNDC()
textDsDecayConj2.SetTextFont(42)
textDsDecayConj2.SetTextSize(0.035)
textDsDecayConj2.Draw()


textEnergy2 = ROOT.TLatex(0.155, 0.85, '#sqrt{#it{s}} = 13.6 Te#kern[-0.05]{V}')
textEnergy2.SetNDC()
textEnergy2.SetTextFont(42)
textEnergy2.SetTextSize(0.035)
#textEnergy.Draw()


textDecay2 = ROOT.TLatex(0.6, 0.88, 'D^{+}#rightarrow #phi#pi^{+}#rightarrow K^{+}K^{#font[122]{-}}#pi^{+} ')
textDecay2.SetNDC()
textDecay2.SetTextFont(42)
textDecay2.SetTextSize(0.035)
textDecay2.Draw()

textDecayConj2 = ROOT.TLatex(0.6, 0.84, 'and charge conj.')
textDecayConj2.SetNDC()
textDecayConj2.SetTextFont(42)
textDecayConj2.SetTextSize(0.035)
textDecayConj2.Draw()

textBR2 = ROOT.TLatex(0.6, 0.8, 'BR unc. (not shown): ^{#lower[5]{+3.7}}_{#lower[-0.2]{#font[122]{-}4.0}}#it{%} ')
textBR2.SetNDC()
textBR2.SetTextFont(42)
textBR2.SetTextSize(0.03)
textBR2.Draw()

Thislegend = ROOT.TLegend(0.6, 0.75, 0.8, 0.78)
Thislegend.SetBorderSize(0)
Thislegend.SetTextSize(0.0285)
Thislegend.SetFillStyle(0)
Thislegend.AddEntry(hRatio, '|#it{y}| < 0.5', 'lp')
Thislegend.Draw()

ThislegendBorder = ROOT.TLegend(0.6, 0.75, 0.8, 0.78)
ThislegendBorder.SetBorderSize(0)
ThislegendBorder.SetTextSize(0.0285)
ThislegendBorder.SetFillStyle(0)
ThislegendBorder.AddEntry(hRatioBorder, '|#it{y}| < 0.5', 'lp')
ThislegendBorder.Draw()

text = ROOT.TLatex(0.42, 0.37, 'D^{+}#rightarrow #pi^{+}K^{#font[122]{-}}#pi^{+}')
text.SetNDC()
text.SetTextFont(42)
text.SetTextSize(0.035)
text.Draw()

textConj = ROOT.TLatex(0.42, 0.33, 'and charge conj.')
textConj.SetNDC()
textConj.SetTextFont(42)
textConj.SetTextSize(0.035)
textConj.Draw()

textBRGoldenDplus = ROOT.TLatex(0.42, 0.29, 'BR unc. (not shown): 3.2#it{%}')
textBRGoldenDplus.SetNDC()
textBRGoldenDplus.SetTextFont(42)
textBRGoldenDplus.SetTextSize(0.03)
textBRGoldenDplus.Draw()

LegLHCbText = ROOT.TLatex(0.42, 0.25, 'LHCb, #sqrt{#it{s}} = 13 Te#kern[-0.05]{V}, JHEP 03 (2016) 159')
LegLHCbText.SetNDC()
LegLHCbText.SetTextFont(42)
LegLHCbText.SetTextSize(0.03)
LegLHCbText.Draw()

legLHCb = ROOT.TLegend(0.42, 0.13, 0.7, 0.23)
legLHCb.SetBorderSize(0)
legLHCb.SetTextSize(0.0285)
legLHCb.SetFillStyle(0)
legLHCb.AddEntry(hLHCb_30_35, '3.0 < #it{y} < 3.5', 'lp')
legLHCb.AddEntry(hLHCb_35_40, '3.5 < #it{y} < 4.0', 'lp')
legLHCb.AddEntry(hLHCb_40_45, '4.0 < #it{y} < 4.5', 'lp')
legLHCb.Draw()

legLHCbBorder = ROOT.TLegend(0.42, 0.13, 0.7, 0.23)
legLHCbBorder.SetBorderSize(0)
legLHCbBorder.SetTextSize(0.0285)
legLHCbBorder.SetFillStyle(0)
legLHCbBorder.AddEntry(hLHCb_30_35Border, '3.0 < #it{y} < 3.5', 'lp')
legLHCbBorder.AddEntry(hLHCb_35_40Border, '3.5 < #it{y} < 4.0', 'lp')
legLHCbBorder.AddEntry(hLHCb_40_45Border, '4.0 < #it{y} < 4.5', 'lp')
legLHCbBorder.Draw()

ROOT.gPad.RedrawAxis()

canvasHighRap.SaveAs('/home/fchinu/Run3/Ds_pp_13TeV/Figures/Ratio/DsOverDplusComparisonLHCbHighRap.png')
canvasHighRap.SaveAs('/home/fchinu/Run3/Ds_pp_13TeV/Figures/Ratio/DsOverDplusComparisonLHCbHighRap.pdf')
canvasHighRap.SaveAs('/home/fchinu/Run3/Ds_pp_13TeV/Figures/Ratio/DsOverDplusComparisonLHCbHighRap.eps')
