inputs:
  sparse:
    file_names: [
        /home/fchinu/Run3/Ds_pp_13TeV/Datasets/Ds_pp_run3_ml/MC/Train360775/AnalysisResults_LHC24h1_0.root
      ]
    axis_pt_gen: 0
    axis_npv_gen: 2
    axis_pt_reco: 1
    axis_npv_reco: 6
    axis_cent_gen: 3
  task_name: 'hf-task-ds' #['hf-task-ds', 'hf-task-ds-WithNPV']
  cutset: '/home/fchinu/Run3/Ds_pp_13TeV/Projections_RawYields/configs/cutset_pp13TeV_multiplicity.yml'

weights:
  apply: False
  file_name: '/home/fchinu/Run3/Ds_pp_13TeV/Efficiency/VsMult/weights_LHC24h1_FT0M.root'
  reweight_on_data_events: False # To apply weights for datasets with different sizes
  data_analysis_results: [
    '/home/fchinu/Run3/Ds_pp_13TeV/Datasets/Ds_pp_run3_ml/Data/Train279067/AnalysisResults_LHC22o_pass7.root',
    [
      '/home/fchinu/Run3/Ds_pp_13TeV/Datasets/Ds_pp_run3_ml/Data/Train290606/AnalysisResults_LHC23_pass4_001.root',
      '/home/fchinu/Run3/Ds_pp_13TeV/Datasets/Ds_pp_run3_ml/Data/Train290606/AnalysisResults_LHC23_pass4_002.root',
      '/home/fchinu/Run3/Ds_pp_13TeV/Datasets/Ds_pp_run3_ml/Data/Train290606/AnalysisResults_LHC23_pass4_003.root',
      '/home/fchinu/Run3/Ds_pp_13TeV/Datasets/Ds_pp_run3_ml/Data/Train290606/AnalysisResults_LHC23_pass4_004.root',
      '/home/fchinu/Run3/Ds_pp_13TeV/Datasets/Ds_pp_run3_ml/Data/Train290606/AnalysisResults_LHC23_pass4_005.root',
      '/home/fchinu/Run3/Ds_pp_13TeV/Datasets/Ds_pp_run3_ml/Data/Train290606/AnalysisResults_LHC23_pass4_006.root',
      '/home/fchinu/Run3/Ds_pp_13TeV/Datasets/Ds_pp_run3_ml/Data/Train290606/AnalysisResults_LHC23_pass4_007.root'
    ]
  ]


verbose: False
output_dir: '/home/fchinu/Run3/Ds_pp_13TeV/Efficiency/VsMult'
suffix: 'LHC24h1' #['FT0M', 'NTracksPV']