python3 /home/fchinu/Run3/ThesisUtils/Plotting.py -c /home/fchinu/Run3/Ds_pp_13TeV/Figures/Variables_Distributions/configs/Mass.yaml
python3 /home/fchinu/Run3/ThesisUtils/Plotting.py -c /home/fchinu/Run3/Ds_pp_13TeV/Figures/Variables_Distributions/configs/ImpactParameter0.yaml
python3 /home/fchinu/Run3/ThesisUtils/Plotting.py -c /home/fchinu/Run3/Ds_pp_13TeV/Figures/Variables_Distributions/configs/Cpa.yaml
python3 /home/fchinu/Run3/ThesisUtils/Plotting.py -c /home/fchinu/Run3/Ds_pp_13TeV/Figures/Variables_Distributions/configs/CpaXY.yaml
python3 /home/fchinu/Run3/ThesisUtils/Plotting.py -c /home/fchinu/Run3/Ds_pp_13TeV/Figures/Variables_Distributions/configs/DecayLength.yaml
python3 /home/fchinu/Run3/ThesisUtils/Plotting.py -c /home/fchinu/Run3/Ds_pp_13TeV/Figures/Variables_Distributions/configs/DecayLengthXY.yaml
python3 /home/fchinu/Run3/ThesisUtils/Plotting.py -c /home/fchinu/Run3/Ds_pp_13TeV/Figures/Variables_Distributions/configs/ImpactParameterXY.yaml
python3 /home/fchinu/Run3/ThesisUtils/Plotting.py -c /home/fchinu/Run3/Ds_pp_13TeV/Figures/Variables_Distributions/configs/DecayLengthDsDplus.yaml
python3 /home/fchinu/Run3/ThesisUtils/Plotting.py -c /home/fchinu/Run3/Ds_pp_13TeV/Figures/Variables_Distributions/configs/AbsCos3PiK.yaml
python3 /home/fchinu/Run3/ThesisUtils/Plotting.py -c /home/fchinu/Run3/Ds_pp_13TeV/Figures/Variables_Distributions/configs/DeltaMassKK.yaml
python3 /home/fchinu/Run3/ThesisUtils/Plotting.py -c /home/fchinu/Run3/Ds_pp_13TeV/Figures/Variables_Distributions/configs/Chi2PCA.yaml