#python3 /home/fchinu/Run3/ThesisUtils/Plotting.py -c /home/fchinu/Run3/Ds_pp_13TeV/Figures/configs/Mass.yaml
python3 /home/fchinu/Run3/ThesisUtils/Plotting.py -c /home/fchinu/Run3/Ds_pp_13TeV/Figures/configs/ImpactParameter0.yaml
#python3 /home/fchinu/Run3/ThesisUtils/Plotting.py -c /home/fchinu/Run3/Ds_pp_13TeV/Figures/configs/Cpa.yaml
#python3 /home/fchinu/Run3/ThesisUtils/Plotting.py -c /home/fchinu/Run3/Ds_pp_13TeV/Figures/configs/CpaXY.yaml
#python3 /home/fchinu/Run3/ThesisUtils/Plotting.py -c /home/fchinu/Run3/Ds_pp_13TeV/Figures/configs/DecayLength.yaml
#python3 /home/fchinu/Run3/ThesisUtils/Plotting.py -c /home/fchinu/Run3/Ds_pp_13TeV/Figures/configs/DecayLengthXY.yaml
#python3 /home/fchinu/Run3/ThesisUtils/Plotting.py -c /home/fchinu/Run3/Ds_pp_13TeV/Figures/configs/ImpactParameterXY.yaml
#python3 /home/fchinu/Run3/ThesisUtils/Plotting.py -c /home/fchinu/Run3/Ds_pp_13TeV/Figures/configs/AbsCos3PiK.yaml
#python3 /home/fchinu/Run3/ThesisUtils/Plotting.py -c /home/fchinu/Run3/Ds_pp_13TeV/Figures/configs/DeltaMassKK.yaml
#python3 /home/fchinu/Run3/ThesisUtils/Plotting.py -c /home/fchinu/Run3/Ds_pp_13TeV/Figures/configs/Chi2PCA.yaml